apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  namespace: demo
spec:
  selector:
    matchLabels:
      app: minio
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: minio
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - node-name
      containers:
      - name: minio
        image: minio/minio:edge      
        args:
        - server
        - /data
        env:
        - name: MINIO_ACCESS_KEY
          value: "xxxxxxxxx"
        - name: MINIO_SECRET_KEY
          valueFrom:
              secretKeyRef:
                name: minio-name-secret
                key: minio_secret_key
        ports:
        - containerPort: 9000
        readinessProbe:
          httpGet:
            path: /minio/health/ready
            port: 9000
          initialDelaySeconds: 120
          periodSeconds: 20
        livenessProbe:
          httpGet:
            path: /minio/health/live
            port: 9000
          initialDelaySeconds: 120
          periodSeconds: 20
        volumeMounts:
          - mountPath: /data
            name: minio-data
      volumes:
        - name: minio-data
          hostPath:
              path: /data
              type: DirectoryOrCreate
